permalink: pretty
theme: jekyll_patternbot
patternbot:
  font_url: "https://use.typekit.net/mty6aqe.css"
  font_url: "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700&display=swap"
