title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
    width: "12em"
  light:
    title: "Light"
    description: |
      The light button is to be as a variation of the main basic button when there is a need to differentiate between the two.
    width: "12em"
  subtle:
    title: "Subtle"
    description: |
      The subtle button is to be used on the shopping cart summary screen before the checkout form to allow the user to take out products they no longer wihs to purchase.
    width: "12em"
  back-to-gallery:
    title: "Back To Gallery"
    description: |
      This secondary navigation option will be placed at the top of the product details page.
