title: "Sections"
description: |
  Sections will be specifically used for the product details page.

patterns:
  product-details-section:
    title: "Product Details Section"
    description: |
      This is the section that will describe the product in detail and provide all necessary information for the customer.
    fields:
      - name: heading
        type: string
        example: "Headings"
      - name: text
        type: string
        example: "Text / Content"
  shopping-summary-section:
    title: "Shopping Summary Section"
    description: |
      This is the section that will provide a summary of the products in the customer's cart and will be featured over the checkout form.
    width: 35em
  section-separation:
    title: "Section Separation Pattern"
    description: |
      This is a pattern to use when there is a need to separate sections from one another.
  content-section:
    title: "Content Section"
    description: |
      This is the section that will have the written content of the webpage.
    width: 32em
    fields:
      - name: heading
        type: string
        example: "Headings"
      - name: heading2
        type: string
        example: "Headings"
      - name: heading3
        type: string
        example: "Headings"
      - name: heading4
        type: string
        example: "Headings"
      - name: heading5
        type: string
        example: "Headings"
      - name: heading6
        type: string
        example: "Headings"
      - name: text
        type: string
        example: "Text / Content"
      - name: text2
        type: string
        example: "Text / Content"
      - name: text3
        type: string
        example: "Text / Content"
      - name: text4
        type: string
        example: "Text / Content"
      - name: text5
        type: string
        example: "Text / Content"
      - name: text6
        type: string
        example: "Text / Content"
  list-section:
    title: "Lists Section"
    description: |
      This is the section that will have the various list patterns that could potentially appear on a website.
    width: 32em
    fields:
      - name: text
        type: string
        example: "Text / Content"
      - name: text2
        type: string
        example: "Text / Content"
      - name: text3
        type: string
        example: "Text / Content"
      - name: text4
        type: string
        example: "Text / Content"
      - name: text5
        type: string
        example: "Text / Content"
      - name: text6
        type: string
        example: "Text / Content"
      - name: text7
        type: string
        example: "Text / Content"
      - name: text8
        type: string
        example: "Text / Content"
      - name: text9
        type: string
        example: "Text / Content"
      - name: text10
        type: string
        example: "Text / Content"
      - name: text11
        type: string
        example: "Text / Content"
      - name: text12
        type: string
        example: "Text / Content"
      - name: text13
        type: string
        example: "Text / Content"
      - name: text14
        type: string
        example: "Text / Content"
      - name: text15
        type: string
        example: "Text / Content"
      - name: text16
        type: string
        example: "Text / Content"
      - name: text17
        type: string
        example: "Text / Content"
      - name: text18
        type: string
        example: "Text / Content"
      - name: text19
        type: string
        example: "Text / Content"
      - name: text20
        type: string
        example: "Text / Content"
      - name: text21
        type: string
        example: "Text / Content"
      - name: text22
        type: string
        example: "Text / Content"
      - name: text23
        type: string
        example: "Text / Content"
      - name: text24
        type: string
        example: "Text / Content"
      - name: text25
        type: string
        example: "Text / Content"
      - name: text26
        type: string
        example: "Text / Content"
      - name: text27
        type: string
        example: "Text / Content"
      - name: text28
        type: string
        example: "Text / Content"
      - name: text29
        type: string
        example: "Text / Content"
      - name: text30
        type: string
        example: "Text / Content"
  table-section:
    title: "Table Section"
    description: |
      This is the section that will have the table pattern that could potentially appear on a website.
    width: 32em
    fields:
      - name: caption
        type: string
        example: "Caption Sentence"
      - name: column
        type: string
        example: "Column"
      - name: column2
        type: string
        example: "Column"
      - name: column3
        type: string
        example: "Column"
      - name: column4
        type: string
        example: "Column"
      - name: column5
        type: string
        example: "Column"
      - name: column6
        type: string
        example: "Column"
      - name: row11
        type: string
        example: "Row 1"
      - name: row12
        type: string
        example: "Row 1.2"
      - name: row13
        type: string
        example: "Row 1.3"
      - name: row14
        type: string
        example: "Row 1.4"
      - name: row15
        type: string
        example: "Row 1.5"
      - name: row16
        type: string
        example: "Row 1.6"
      - name: row21
        type: string
        example: "Row 2"
      - name: row22
        type: string
        example: "Row 2.2"
      - name: row23
        type: string
        example: "Row 2.3"
      - name: row24
        type: string
        example: "Row 2.4"
      - name: row25
        type: string
        example: "Row 2.5"
      - name: row26
        type: string
        example: "Row 2.6"
      - name: row31
        type: string
        example: "Row 3"
      - name: row32
        type: string
        example: "Row 3.2"
      - name: row33
        type: string
        example: "Row 3.3"
      - name: row34
        type: string
        example: "Row 3.4"
      - name: row35
        type: string
        example: "Row 3.5"
      - name: row36
        type: string
        example: "Row 3.6"
      - name: row41
        type: string
        example: "Row 4"
      - name: row42
        type: string
        example: "Row 4.2"
      - name: row43
        type: string
        example: "Row 4.3"
      - name: row44
        type: string
        example: "Row 4.4"
      - name: row45
        type: string
        example: "Row 4.5"
      - name: row46
        type: string
        example: "Row 4.6"
      - name: row51
        type: string
        example: "Row 5"
      - name: row52
        type: string
        example: "Row 5.2"
      - name: row53
        type: string
        example: "Row 5.3"
      - name: row54
        type: string
        example: "Row 5.4"
      - name: row55
        type: string
        example: "Row 5.5"
      - name: row56
        type: string
        example: "Row 5.6"
      - name: row61
        type: string
        example: "Row 6"
      - name: row62
        type: string
        example: "Row 6.2"
      - name: row63
        type: string
        example: "Row 6.3"
      - name: row64
        type: string
        example: "Row 6.4"
      - name: row65
        type: string
        example: "Row 6.5"
      - name: row66
        type: string
        example: "Row 6.6"
