title: "Sections"
description: |
  Sections will be specifically used for the product details page.

patterns:
  product-details-section:
    title: "Product Details Section"
    description: |
      This is the section that will describe the product in detail and provide all necessary information for the customer.
  shopping-summary-section:
    title: "Shopping Summary Section"
    description: |
      This is the section that will provide a summary of the products in the customer's cart and will be featured over the checkout form.
    width: 35em
