title: "Cards"
description: |
  Cards should be used to display various similar options available to the user.

patterns:
  collections-card:
    title: "Collections Cards"
    description: |
      There are three collections featured in this website: Earthenware, Stoneware and Porcelain. These cards are featured on the home / landing page.
    width: 25em
  gallery-cards:
    title: "Gallery Cards"
    description: |
      These are the main cards to be used in the gallery section to link to a variety of product pages.
    width: 25em
  add-to-cart-overlay:
    title: "Add-To-Cart Overlay"
    description: |
      This will be used to confirm that the customer clicked on the Add To Cart button on the Product Details Page and will confirm that the client wants this item in their shopping cart.
    width: 35em
