title: "Navigation"
description: |
  Navigation will be present in the header and the footer of the website pages.

patterns:
  header:
    title: "Header"
    description: |
      This is the main header pattern present at the top of every page.
  footer:
    title: "Footer"
    description: |
      This is the main footer pattern present at the bottom of every page.
