title: "Secondary Navigation"
description: |
  The secondary navigation will be present at the top of every product details page to allow the customer to go back to the main gallery products page.

patterns:
  back-to-gallery:
    title: "Back To Gallery"
    description: |
      This secondary navigation option will be placed at the top of the product details page.
