title: "Banners"
description: |
  Banners should be used at the top of every page (other than the checkout page).

patterns:
  banner-btn:
    title: "Landing Page Banner"
    description: |
      This is the banner that will be used on the home / landing page.
    fields:
      - name: heading
        type: string
        example: "Unique. Unusual. Urban."
      - name: text
        type: string
        example: "Find the perfect ceramic piece to complete your collection."
      - name: button-text
        type: string
        example: "View Products"
        required: false
      - name: button_url
        type: url
        example: "/gallery/"
        required: false
  featured-products-banner:
    title: "Featured Products Page Banner"
    description: |
      This is the banner that will be used on the featured products section.
  product-list-banner:
    title: "Product List Banner"
    description: |
      This is the banner that will be used on the products list page.
    fields:
      - name: heading
        type: string
        example: "View the gallery"
      - name: text
        type: string
        example: "Browse our gallery to find that perfect piece of art."
  commissions-banner:
    title: "Commissions Banner"
    description: |
      This banner will be present underneath the gallery and each product details page.
    fields:
      - name: heading
        type: string
        example: "Commissions are welcome!"
      - name: text
        type: string
        example: "Send us a quick message to let us know if you require custom work done."
      - name: button-text
        type: string
        example: "Contact Us"
        required: false
      - name: button_url
        type: url
        example: "/contact/"
        required: false
